env:
  es6: true
  node: true
  browser: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
